# Generated by Django 2.1 on 2019-10-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebotapp', '0003_description_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='description',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradebotapp.FeatureCategory'),
        ),
    ]
