# Generated by Django 2.1 on 2019-10-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebotapp', '0004_auto_20191006_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='fontawesome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='svg_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
